include_recipe 'adam_snark_rabbit::base'
include_recipe 'adam_snark_rabbit::rabbitmq'
include_recipe 'adam_snark_rabbit::xmpp'
include_recipe 'adam_snark_rabbit::mongo'
include_recipe 'adam_snark_rabbit::app'
