---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: tdb-ubuntu
  driver_config:
    box: tdb-ubuntu1204-v14
    box_url: http://ci.mojolingo.com/job/Telephony-Dev-Box-Base-Boxen/14/artifact/tdb-ubuntu1204.box
    customize:
      memory: 1024
- name: opscode-debian-7.1
  driver_config:
    box: debian
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box
    customize:
      memory: 1024

suites:
- name: default
  run_list: ['recipe[adam_snark_rabbit]']
  attributes:
    adam:
      deploy_key: <%= File.read('deploy_key').inspect %>
