---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: tdb-ubuntu
  driver_config:
    box: tdb-ubuntu1204-v9
    box_url: http://ci.mojolingo.com/job/Telephony-Dev-Box-Base-Boxen/9/artifact/tdb-ubuntu1204.box
    customize:
      memory: 1024

suites:
- name: default
  run_list: ['recipe[adam_snark_rabbit]']
  attributes:
    adam:
      deploy_key: <%= File.read('deploy_key').inspect %>
      memory:
        application_servers:
        - ipaddress: '127.0.0.1'
