---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: debian-7.4

suites:
- name: default
  run_list: ['recipe[adam_snark_rabbit]']
  attributes:
    adam:
      deploy_key: <%= File.read('deploy_key').inspect %>
